export const ActionTypes={
    SET_USER:"SET_USER",
    SET_TAB:"SET_TAB",
    SET_SONG:"SET_SONG",
    SET_SONG_LOADING:"SET_SONG_LOADING",
    SET_LYRICS_LOADING:"SET_LYRICS_LOADING",
    SET_LYRICS:"SET_LYRICS"
   

}